spring:
  application:
    name: "FinalTrain"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${DB_URL1}
    username : ${DB_USER}
    password: ${DB_PASSWORD}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl