spring:
  application:
    name: "FinalTrain"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${DB_URL1}
    username : ${DB_USER}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    dashscope:
      api-key: sk-e323695fe67a43de87bf702c3f36bd28
      chat:
        options:
          model: qwen-plus

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
